_mainIndex:
    pattern: /
    defaults: {_controller: ISGProjectSubmissionAppBundle:Test:new }

_user_enter:
    pattern: /user/enter.php
    defaults : {_controller: ISGProjectSubmissionAppBundle:User:enter }    

_user_show:
    pattern:  /user/show/{name}
    defaults: { _controller: ISGProjectSubmissionAppBundle:User:show }

    
    